### ISSUE TITLE
Where to find the thesis

### ISSUE THREAD

**Issue by Vurgit** [HaleyRoss/CurrentLimit-PowerSystemStability#1]
Hi there, how can I find the corresponding thesis?

**Comment by HaleyRoss** [comment]
[Inverter Current Limiting Impacts on Power System Stability](https://scholar.colorado.edu/concern/graduate_thesis_or_dissertations/2227mr36d)

Please find a copy of the thesis above. Apologies for the delay, I had to wait for the document to be released open source and wasn't told when that would be.
